### ISSUE TITLE
There seems to be something wrong with the alembic

### ISSUE THREAD

**Issue by rimbi** [zeenix/gimoji#14]
I copied alembic ⚗️ to the clipboard and then pasted it to the console (iterm2) and here is what I see:

<img width="412" alt="image" src="https://github.com/zeenix/gimoji/assets/51825/9673b09a-ea1b-4f7f-bb12-4f6d5eaf876e">

That does not happen with, for instance, lock icon:
<img width="202" alt="image" src="https://github.com/zeenix/gimoji/assets/51825/83659624-a4ab-4f30-9c71-1aba96b7c4c0">

Also, it looks ok when I paste the alembic to another medium, such as here: ⚗️

One more thing: I have noticed that with lock, there is a space between the icon and `to` in the message `Copied 🔒️ to the clipboard`, while with alembic it does not exist.

**Comment by zeenix** [comment]
Thanks for reporting this. 

That's strange indeed. gimoji is just taking the UTF-8 string/character verbatim from the emoji db provided by [gitmoji](https://github.com/carloscuesta/gitmoji) project. One thing you can do to check if the issue is in the DB, is C&P from the db directly (file `~/.cache/gimoji/emojis.json`, you may need to adjust the path if Mac uses a different cache dir). If it is, the issue should be reported to gitmoji then.

Down the line, we may provide our own db.

**Comment by zeenix** [comment]
@rimbi I know you went down a rabbit hole with this one but don't forget the original intention of quickly finding out the cache location. :wink:

**Comment by zeenix** [comment]
> First of all, the `entity` value for the `alembic` in the cache and thus in the gitmoji url is wrong but it is irrelevant to pur issue.

Could you please report that to [gitmoji](https://github.com/carloscuesta/gitmoji)?

> When pasted, the terminal uses the first code `&#9879;` to display the alembic and prints the second code `&#65039;` as `fe0f`

So gimoji copies two characters into the clipboard? :thinking:

**Comment by rimbi** [comment]
Yes and I have created an issue on gitmoji.

Btw, I have used another similar tool `moji` and I see the same behaviour.

I think the problem is related to the terminal's handling of the pasted character.

The following experiment seems to support my hypothesis:

<img width="286" alt="image" src="https://github.com/zeenix/gimoji/assets/51825/3159ef1f-0d12-43fb-b43a-a51a3cc43a05">

`echo`ing the pasted character results in the correct emoji.

I believe we can close this issue.

**Comment by zeenix** [comment]
@rimbi Ah ok, thanks so much for investigating this. :pray: 

On a related note, I've decided to make the emoji db part of the binary itself and keep a clone of the gitmoji's json in the source. The emoji list is small enough (and unlikely to grow a lot) so it's ok even if our fork had to diverge. Each time emojis are update (rarely), we'll roll out a release. So instead of `gimoji -u`, people will just do `cargo install -f gimoji` (although I'm hoping that we can package for most distros and Mac soon so the update is handled by package managers.
